version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-practise"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8wjgyzes66q4"
s3_prefix = "aws-sam-practise"
region = "ap-northeast-1"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"prod\""
