AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-practise

  Sample SAM Template for aws-sam-practise

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 30

Resources:
  DefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  DefaultApi:
    Description: "API Gateway endpoint URL for Prod stage for Default function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  DefaultFunction:
    Description: "Default Lambda Function ARN"
    Value: !GetAtt DefaultFunction.Arn
  DefaultFunctionIamRole:
    Description: "Implicit IAM Role created for Default function"
    Value: !GetAtt DefaultFunctionRole.Arn
