AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-practise

  Sample SAM Template for aws-sam-practise

Parameters:
  Env:
    Type: String
    Default: local
    AllowedValues:
      - prod
      - local

Mappings:
  EnvMap:
    prod:
      AwsRegion: 'ap-northeast-1'
    local:
      AwsRegion: 'us-west-1'

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 30
    Environment:
      Variables:
        REGION: !FindInMap [ EnvMap, !Ref Env, AwsRegion ]
        DYNAMODB_HOST: !Sub "https://dynamodb.${AWS::Region}.amazonaws.com"
        DYNAMODB_TABLE: !Ref DefaultApiDynamo
#        DYNAMODB_HOST: 'http://172.18.0.1:18000'
#        DYNAMODB_TABLE: 'messages'

Resources:
  DefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies: AmazonDynamoDBFullAccess
      Events:
        Get:
          Type: Api
          Properties:
            Path: /{id}/{user_id}
            Method: get
        Create:
          Type: Api
          Properties:
            Path: /c
            Method: post
        Delete:
          Type: Api
          Properties:
            Path: /d/{id}/{user_id}
            Method: delete

  DefaultApiDynamo:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: user_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  DefaultApi:
    Description: "API Gateway endpoint URL for Prod stage for Default function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  DefaultFunction:
    Description: "Default Lambda Function ARN"
    Value: !GetAtt DefaultFunction.Arn
  DefaultFunctionIamRole:
    Description: "Implicit IAM Role created for Default function"
    Value: !GetAtt DefaultFunctionRole.Arn
  DefaultApiDynamo:
    Description: "User Connections Api DynamoDB ARN"
    Value: !GetAtt DefaultApiDynamo.Arn
